/**
 * StoryNarrative — Rich rendering of structured narrative entries.
 *
 * Recorder-based view: renders CombinedNarrativeRecorder output with
 * progressive reveal synced to snapshot index. Each entry is typed
 * (stage, step, condition, fork, subflow, loop, break, error) and
 * rendered with appropriate icon + indentation.
 *
 * Data source: FlowRecorder (fires AFTER stage execution)
 */
import { useMemo, useRef, useEffect } from "react";
import type { NarrativeEntry, BaseComponentProps } from "../../types";
import { theme, fontSize, padding } from "../../theme";

export interface StoryNarrativeProps extends BaseComponentProps {
  /** Structured narrative entries from CombinedNarrativeRecorder */
  entries: NarrativeEntry[];
  /** Number of entries to reveal (position-based sync from NarrativePanel) */
  revealedEntryCount: number;
}

const ENTRY_ICONS: Record<string, { icon: string; color: string; label: string }> = {
  stage:     { icon: "▸", color: theme.primary,       label: "Stage" },
  step:      { icon: "·", color: theme.textMuted,      label: "Data operation" },
  condition: { icon: "◇", color: theme.warning,        label: "Decision" },
  fork:      { icon: "⑃", color: theme.primary,       label: "Parallel" },
  subflow:   { icon: "↳", color: theme.textSecondary,  label: "Subflow" },
  loop:      { icon: "↻", color: theme.warning,        label: "Loop" },
  break:     { icon: "■", color: theme.error,          label: "Break" },
  error:     { icon: "✗", color: theme.error,          label: "Error" },
};

export function StoryNarrative({
  entries,
  revealedEntryCount,
  size = "default",
  unstyled = false,
  className,
  style: outerStyle,
}: StoryNarrativeProps) {
  const fs = fontSize[size];
  const pad = padding[size];

  // Position-based reveal: NarrativePanel computes the cut point based on
  // section boundaries (stage entries). This handles loops (same stageId,
  // different iterations) and subflow repeats correctly.
  const revealedCount = revealedEntryCount;

  // Filter revealed entries: show root-level entries + subflow Entering/Exiting markers.
  // Subflow internal entries (stage, step, condition inside a subflow) are hidden —
  // they appear in the drill-down view.
  const revealed = useMemo(() => {
    const raw = entries.slice(0, revealedCount);
    return raw.filter((e) => {
      const sfId = (e as { subflowId?: string }).subflowId;
      if (!sfId) return true; // root-level — always show
      if (e.type === "subflow") return true; // Entering/Exiting markers — show
      return false; // internal subflow entries — hide (drill-down only)
    });
  }, [entries, revealedCount]);
  // Future count: only count entries that would actually be shown (same filter as revealed)
  const futureCount = useMemo(() => {
    let count = 0;
    for (let i = revealedCount; i < entries.length; i++) {
      const e = entries[i] as { subflowId?: string };
      if (!e.subflowId || entries[i].type === "subflow") count++;
    }
    return count;
  }, [entries, revealedCount]);

  const latestRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    latestRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [revealed.length]);

  // Compute heading numbers and clean text for each revealed entry.
  // Root stages/conditions count sequentially (1, 2, 3...).
  // Subflow entries get sub-numbers (3.1, 3.2) under the parent counter.
  const numberedEntries = useMemo(() => {
    let rootCounter = 0;
    let subflowChildCounter = 0;
    let lastRootForSubflow = 0;

    let prevType = "";
    return revealed.map((entry) => {
      const isStageHeading = entry.type === "stage";
      const isConditionHeading = entry.type === "condition";
      // First fork entry in a sequence = selector heading (don't count subsequent forks)
      const isForkHeading = entry.type === "fork" && prevType !== "fork";
      const isHeading = isStageHeading || isConditionHeading || isForkHeading;
      const isSubflowMarker = entry.type === "subflow";

      prevType = entry.type;

      // Strip "Stage N: " prefix from text (generated by CombinedNarrativeRecorder)
      let cleanText = entry.text;
      cleanText = cleanText.replace(/^Stage \d+:\s*/, "");
      // Strip "[Selected]: " and "[Parallel]: " prefixes for cleaner headings
      cleanText = cleanText.replace(/^\[(Selected|Parallel)\]:\s*/, "");

      if (isHeading) {
        rootCounter++;
        subflowChildCounter = 0;
        lastRootForSubflow = rootCounter;

        const typeLabel = isConditionHeading ? "Decider" : isForkHeading ? "Selector" : "Stage";
        return { ...entry, heading: `${typeLabel} ${rootCounter}`, text: cleanText, isHeading: true };
      }

      // Subsequent fork entries (e.g. [Parallel] after [Selected]) — no heading, just show
      if (entry.type === "fork") {
        return { ...entry, heading: null, isHeading: false, text: cleanText };
      }

      if (isSubflowMarker && entry.text.startsWith("Entering")) {
        subflowChildCounter++;
        // Extract subflow name from "Entering the X subflow: description"
        const sfMatch = entry.text.match(/Entering the (.+?) subflow/);
        const sfName = sfMatch?.[1] ?? "Subflow";
        const sfDesc = entry.text.replace(/^Entering the .+? subflow[.:]\s*/, "").replace(/\.$/, "");
        return {
          ...entry,
          heading: `Subflow ${rootCounter + 1}.${subflowChildCounter}`,
          text: sfDesc ? `${sfName} — ${sfDesc}` : sfName,
          isHeading: true,
          isSubflow: true,
        };
      }

      return { ...entry, heading: null, isHeading: false };
    });
  }, [revealed]);

  if (unstyled) {
    return (
      <div className={className} style={outerStyle} data-fp="story-narrative" role="log">
        {numberedEntries.map((entry, i) => (
          <div key={i} data-fp="narrative-entry" data-type={entry.type}>
            {entry.heading ? `${entry.heading}: ${entry.text}` : entry.text}
          </div>
        ))}
      </div>
    );
  }

  return (
    <div
      className={className}
      style={{
        flex: 1,
        overflow: "auto",
        padding: pad,
        fontFamily: theme.fontSans,
        ...outerStyle,
      }}
      data-fp="story-narrative"
      role="log"
      aria-label="Execution narrative"
    >
      {numberedEntries.map((entry, i) => {
        const meta = ENTRY_ICONS[entry.type] ?? ENTRY_ICONS.step;
        const isStage = entry.isHeading;
        const isDecision = entry.type === "condition";
        const isError = entry.type === "error";
        const isSubflow = (entry as any).isSubflow;
        const isLast = i === numberedEntries.length - 1;
        // Skip "Exiting" subflow markers — Entering is enough
        if (entry.type === "subflow" && entry.text.startsWith("Exiting")) return null;

        return (
          <div
            key={i}
            ref={isLast ? latestRef : undefined}
            style={{
              display: "flex",
              gap: 8,
              padding: isStage ? `${pad - 4}px 0` : `2px 0`,
              marginLeft: isSubflow ? 16 : entry.depth * 16,
              borderBottom: isStage && !isSubflow ? `1px solid ${theme.border}` : undefined,
              marginTop: isStage && i > 0 ? 8 : 0,
            }}
          >
            <span
              style={{
                color: meta.color,
                fontWeight: 700,
                fontSize: isStage ? fs.body : fs.small,
                width: 16,
                textAlign: "center",
                flexShrink: 0,
              }}
              title={meta.label}
              aria-label={meta.label}
            >
              {meta.icon}
            </span>
            <span
              style={{
                fontSize: isStage ? fs.body : fs.small,
                fontWeight: isStage ? 600 : 400,
                color: isError
                  ? theme.error
                  : isDecision
                    ? theme.warning
                    : isStage
                      ? theme.textPrimary
                      : theme.textSecondary,
                lineHeight: 1.6,
                fontFamily: entry.type === "step" ? theme.fontMono : theme.fontSans,
              }}
            >
              {entry.heading ? <><strong>{entry.heading}:</strong> {entry.text}</> : entry.text}
            </span>
          </div>
        );
      })}

      {/* Future entries — show count hint only, skip full rendering for performance */}
      {futureCount > 0 && (
        <div style={{
          opacity: 0.3,
          fontSize: fs.small,
          color: theme.textMuted,
          padding: `8px 0`,
          fontStyle: "italic",
        }}>
          {futureCount} more {futureCount === 1 ? "entry" : "entries"} ahead...
        </div>
      )}
    </div>
  );
}
